package com.example.passportphotomaker.domain.model

import android.graphics.RectF

data class Landmark(val x: Float, val y: Float, val z: Float)

data class FaceData(
    val boundingBox: RectF,
    val landmarks: List<Landmark>,
    
    // 1. The raw 2D skin mask generated by the TFLite model
    val segmentationMask: Array<FloatArray>,
    
    // 2. Image dimensions
    val width: Int,
    val height: Int,
    
    // 3. The 9 flat 1D FloatArray masks required by the C++ engine
    val refinedMask: FloatArray,
    val sharpMask: FloatArray,
    val blemishMask: FloatArray,
    val brightnessMask: FloatArray,
    val eyebrowMask: FloatArray,
    val eyesMask: FloatArray,
    val eyeBagsMask: FloatArray,
    val irisMask: FloatArray,
    val teethMask: FloatArray
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as FaceData

        if (width != other.width) return false
        if (height != other.height) return false
        if (boundingBox != other.boundingBox) return false
        if (!segmentationMask.contentDeepEquals(other.segmentationMask)) return false
        if (!refinedMask.contentEquals(other.refinedMask)) return false
        if (!sharpMask.contentEquals(other.sharpMask)) return false
        if (!blemishMask.contentEquals(other.blemishMask)) return false
        if (!brightnessMask.contentEquals(other.brightnessMask)) return false
        if (!eyebrowMask.contentEquals(other.eyebrowMask)) return false
        if (!eyesMask.contentEquals(other.eyesMask)) return false
        if (!eyeBagsMask.contentEquals(other.eyeBagsMask)) return false
        if (!irisMask.contentEquals(other.irisMask)) return false
        if (!teethMask.contentEquals(other.teethMask)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = width
        result = 31 * result + height
        result = 31 * result + boundingBox.hashCode()
        result = 31 * result + segmentationMask.contentDeepHashCode()
        result = 31 * result + refinedMask.contentHashCode()
        result = 31 * result + sharpMask.contentHashCode()
        result = 31 * result + blemishMask.contentHashCode()
        result = 31 * result + brightnessMask.contentHashCode()
        result = 31 * result + eyebrowMask.contentHashCode()
        result = 31 * result + eyesMask.contentHashCode()
        result = 31 * result + eyeBagsMask.contentHashCode()
        result = 31 * result + irisMask.contentHashCode()
        result = 31 * result + teethMask.contentHashCode()
        return result
    }
}
